config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  Rails.application.routes.default_url_options[:host] = Rails.application.secrets.dig(:load_balancer_address)

  root "home#index"
  get "/public_key", to: "static#public_key"
  get "/authorize_upload", to: "static#authorize_upload"
  post "/sign", to: "signatures#create"

  resources :profiles, path: "/u", only: :show do
  end

  resource :setting, only: :update

  resource :profile, only: [] do
    post "/reset_counter", action: :reset_counter
  end

  resources :notifications, only: :index do
    collection do
      patch "/mark_as_seen", action: :mark_as_seen
      delete "/", action: :destroy
    end
  end

  resources :verification_results, only: %i(create update show) do
    collection do
      post "/search", action: :index
    end
  end

  resources :posts, except: :create do
    collection do
      post "/upload", action: :create
    end
  end
  resources :previous_searches, only: %i(index create destroy)
  resources :image_albums, only: %i(index show create update destroy) do
    resources :gallery_elements, only: %i(index) do
      collection do
        post "/upload", action: :create
      end
    end
  end

  resources :gallery_elements, only: :destroy do
    collection do
      get "/all_private_file_names", action: :all_private_file_names
      get "/all_md5_checksums", action: :all_md5_checksums
    end
  end

  resources :cities, only: %i(index)
  resources :identities, only: :create do
    collection do
      post "/ping", action: :ping
    end
  end
  resources :peer_infos, only: %i(index show create update destroy) do
    collection do
      post "/search_public_keys", action: :search_public_keys
    end
  end

  resource :sessions, only: [] do
    collection do
      get "/profile", action: :profile
      patch "/profile_upload", action: :profile_post
      post "/profile_remove_video", action: :profile_remove_video

      get "/settings", action: :settings

      get "/login", action: :login
      post "/login", action: :login_post

      get "/register", action: :register
      post "/register", action: :register_post

      delete "/logout", action: :logout

      get "/recovery", action: :recovery
      post "/recovery", action: :confirm_recovery
    end
  end

  namespace :mobile do
    resources :notifications, only: :index
  end

  namespace :api do
    post "/server_proof_of_work", to: "server_proof_of_works#show"
    resources :feed_items, only: %i(create destroy)
    resource :friendship, only: %i(show create destroy update)
    resources :friendships, only: %i(index)
    resource :profile, only: :show
    resource :conversations, only: %i(create update)
    resources :messages, only: %i(create update)

    resources :posts, only: %i(show index)

    resources :stories, only: :show

    resources :reactions, only: %i(index create destroy update) do
      collection do
        post "/proof", action: :proof
      end
    end
    resources :comments, only: %i(index show create destroy update)
  end

  namespace :client do
    resources :friendships, only: %i(create destroy update)
    resources :cache_reactions, only: %i(create update destroy) do
      collection do
        post "/search", action: :index
      end
    end

    resources :cache_comments, only: %i(destroy) do
      collection do
        post "/upload", action: :create
        patch "/upload", action: :update
      end
    end
    resources :conversations, only: %i(index create update show) do
      resources :messages, only: %i(index) do
        collection do
          post "/upload", action: :create
        end
      end
    end
    resources :messages, only: %i(update)
  end

  constraints LoggedIn do
    if ENV["DEVELOPER"].present?
      mount Sidekiq::Web => "/sidekiq"
      mount RailsAdmin::Engine => "/admin", as: "rails_admin"
    end
    mount PgHero::Engine => "/pghero"
  end

  if Rails.env.development?
    resources :documentations, path: "/doc", only: %i(index) do
      member do
        get "/:file_name", action: :show, as: :show
      end
    end
  end

  match "/*match", to: "static#not_found", via: :all, constraints: ->(req) do
    req.path.exclude?("auth/auth0") &&
      req.path.exclude?("packs") &&
      req.path.exclude?("rails")
  end
end

app/views/page/_flash.html.erb
<% if flash[:notice].present? %>
  <meta name="flash-notice" content="<%= flash[:notice] %>">
<% end %>
<% if flash[:error].present? %>
  <meta name="flash-error" content="<%= flash[:error] %>">
<% end %>

app/views/page/_footer.html.erb
<div class="mx-auto px-4 w-full md:w-2/3 mb-6">
  <div class="text-center">
  </div>
  <div class="flex justify-center text-center">
    <%= link_to "https://github.com/personal-social-media/personal-social-media", class: "text-black mx-2", target: :_blank do %>
      <%= fa_icon "github 2x" %>
      <div>
        Source
      </div>
    <% end %>

    <%= link_to "https://raw.githubusercontent.com/personal-social-media/personal-social-media/master/LICENSE", class: "text-black mx-2", target: :_blank do %>
      <%= fa_icon "file 2x" %>
      <div>
        License
      </div>
    <% end %>
  </div>

  <div class="text-center mt-4 text-sm">
    <%= link_to "Personal Social Media", "https://personalsocialmedia.net", target: :_blank %> © <%= Time.new.year %>
  </div>
</div>

app/views/page/_modal.html.erb
<%= stimulus_controller :div, "utils/modal" do %>
  <%= button %>

  <div data-utils--modal-target="content" data-action="click->utils--modal#close" class="hidden fixed modal-container overflow-y-scroll pb-32" style="z-index: 1001">
    <div class="mx-auto mt-32 w-1/3 bg-white shadow-xl rounded border border-solid border-gray-200 p-4">
      <%= content %>
    </div>
  </div>

  <%= stimulus_target :div, "utils/modal", :background, class: "bg-gray-600 fixed hidden opacity-50", style: "z-index: 1000" %>
<% end %>

app/views/page/_navbar.html.erb
<div class="mb-24">
  <div class="fixed pt-5 navbar right-0 <%= settings.ui_sidebar_opened_helper ? "" : "left-0" %> pb-1 z-40" data-layout--sidebar-target="navbar">
    <div class="bg-white rounded-lg shadow-lg mr-4 <%= settings.ui_sidebar_opened_helper ? "" : "ml-4" %> px-2 py-4 h-16 flex items-center justify-between" data-layout--sidebar-target="navbarContent">
      <div class="flex items-center">
        <button data-action="click->layout--sidebar#toggleOpen" data-layout--sidebar-target="openButton" class="mr-2 text-gray-700 hover:text-gray-900 <%= settings.ui_sidebar_opened_helper ? "hidden" : "" %>">
          <%= fa_icon "bars 2x" %>
        </button>

        <div class="text-gray-700">
          <%= @title %>
        </div>
      </div>

      <div class="flex items-center">
        <div class="mr-8">
          <%= react_component "top-search" %>
        </div>

        <div class="mx-3">
          <%= react_component "top-conversations" %>
        </div>

        <div class="mx-3">
          <%= react_component "top-notifications", notifications_not_seen_count: current_user.not_seen_notifications_count %>
        </div>

        <div class="ml-5">
          <%= link_to profile_path(current_user.peer_info) do %>
            <%= render Person::AvatarComponent.new(profile: current_user, image_size: :thumbnail,
                                                   video: {
                                                     autoplay: true
                                                   },
                                                   class: "h-12 w-12 rounded-full object-cover object-center") %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/page/_navbar_mobile.html.erb
<%= react_component "navbar-mobile", logoUrl: image_path("logos/psm.svg") %>

<div class="h-32"></div>

app/views/page/_public_key_tag.html.erb
<meta name="public-key" content="<%= Base32.encode(SignaturesService::Sign.new("").public_key) %>">
<meta name="gateway" content="<%= URI.parse(Rails.application.secrets.dig(:load_balancer_address)).host %>">

app/views/page/_sidebar.html.erb
<div class="bg-white h-screen w-56 fixed shadow-lg pt-2 px-2 <%= settings.ui_sidebar_opened_helper ? "" : "hidden" %>" data-layout--sidebar-target="sidebar">
  <div>
    <%= link_to root_path do %>
      <%= image_tag("logos/psm.svg", alt: "logo", class: "h-20 w-20 mx-auto") %>
    <% end %>

    <button data-action="click->layout--sidebar#toggleOpen" class="absolute text-gray-700 hover:text-gray-900">
      <%= fa_icon "bars 2x" %>
    </button>
  </div>

  <div class="pl-2 mt-4 text-gray-700 hover:text-gray-900">
    <div class="text-lg select-none">
      Menu
    </div>

    <div class="mt-4">
      <%= link_to root_path do %>
        <div class="flex items-center">
          <%= fa_icon "home 2x" %> <span class="ml-1 text-sm">Home</span>
        </div>
      <% end %>
    </div>

    <div class="mt-6">
      <div class="my-6">
        <%= link_to root_path do %>
          <div class="flex items-center">
            <%= fa_icon "envelope-square 2x" %> <span class="ml-1 text-sm">Messages</span>
          </div>
        <% end %>
      </div>
      <div class="my-6">
        <%= link_to profile_sessions_path do %>
          <div class="flex items-center">
            <%= fa_icon "user 2x" %> <span class="ml-1 text-sm">Edit Profile</span>
          </div>
        <% end %>
      </div>
      <div class="my-6">
        <%= link_to root_path do %>
          <div class="flex items-center">
            <%= fa_icon "cog 2x" %> <span class="ml-1 text-sm">Settings</span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>